[build]
  publish = "nappsSite"
  functions = "nappsSite/netlify/functions"
  command = "npm install"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    X-Frame-Options = "ALLOWALL"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
